# Generated by Django 4.1.5 on 2023-02-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_carreras_profedores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profedores',
            new_name='Profesores',
        ),
    ]
