# Generated by Django 4.1.5 on 2023-02-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_rename_duracion_carreras_camada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='camada',
            field=models.IntegerField(max_length=4),
        ),
    ]
