# Generated by Django 4.1.5 on 2023-02-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_alter_carreras_camada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreras',
            name='camada',
        ),
    ]
